sonar.projectKey=INSERIRE_PROJECT_KEY
sonar.organization=INSERIRE_ORGANIZATION
sonar.projectName=Adventure Time
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.sourceEncoding=UTF-8
