sonar.projectKey=SammySignorile_adventure-time
sonar.organization=sammysignorile
sonar.projectName=Adventure Time
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
sonar.sourceEncoding=UTF-8
