ui.mode=GUI
app.mode=FULL
persistence.mode=FILESYSTEM
filesystem.path=data/adventure-time.dat
db.url=jdbc:mysql://localhost:3306/adventuretimedb?serverTimezone=Europe/Rome
db.user=root
db.password=root
gui.width=960
gui.height=680
