ui.mode=GUI
app.mode=FULL
persistence.mode=DB
filesystem.path=data/adventure-time.dat
hotel.images.path=${user.home}/Desktop/AdventureTimeImages
db.url=jdbc:mysql://localhost:3306/adventuretimedb?serverTimezone=Europe/Rome
db.user=root
db.password=root
gui.width=960
gui.height=680
