@startuml
[*] --> NessunaRicerca
NessunaRicerca --> RisultatiInBuffer : search()
RisultatiInBuffer --> HotelSelezionato : selectHotel()
HotelSelezionato --> Preventivo : quote()
Preventivo --> HotelSelezionato : modifica extra/punti
Preventivo --> Confermata : confirm() + disponibile
Preventivo --> RisultatiInBuffer : hotel non più disponibile
Confermata --> NessunaRicerca : clearBookingFlow()
RisultatiInBuffer --> NessunaRicerca : logout
HotelSelezionato --> NessunaRicerca : logout
@enduml
