@startuml
left to right direction
actor Viaggiatore
actor Venditore
rectangle "Adventure Time" {
  usecase "Login" as UC1
  usecase "Gestire una prenotazione" as UC2
  usecase "Prenotare" as UC3
  usecase "Gestire prenotazioni ricevute" as UC4
}
Viaggiatore --> UC1
Viaggiatore --> UC2
Venditore --> UC1
Venditore --> UC4
UC3 -|> UC2
@enduml
